### ISSUE TITLE
Error after upgrading to 1.1.1

### ISSUE THREAD

**Issue by alecrt** [sketch7/signalr-client#37]
I get the following error after upgrading library to version 1.1.1
Was working fine with version 1.1.0

```
113 import { HubConnectionFactory } from '@ssv/signalr-client';
                                         ~~~~~~~~~~~~~~~~~~~~~

ERROR in app/app.module.ts(305,5): Error during template compile of 'AppModule'
Could not resolve @ssv/signalr-client relative to [object Object]..
Cannot find module '@ssv/signalr-client'
```

**Comment by alecrt** [comment]
I can confirm that in the npm package https://registry.npmjs.org/@ssv/signalr-client/-/signalr-client-1.1.1.tgz both "bundles" and "es2015" folders are missing.

**Comment by stephenlautier** [comment]
@alecrt ah oki good to know. 
For now just lock it to `1.1.0` as the `1.1.1` doesnt introduce any new fixes or features, just chore updates and we updated our builder (microbundler) which most probably that's the issue.

Quick question, you don't use it angular? or more specifically you don't use it with any SSR?

**Comment by alecrt** [comment]
I use it in Angular 8.2.2 AoT, no SSR

**Comment by stephenlautier** [comment]
@alecrt ah ok, unfortunately, we are still consuming some versions older due to SSR error with `@aspnet/signlar` due to this long hanging issue https://github.com/aspnet/AspNetCore/issues/10400

When we get some time we try to implement mock version for SSR which hopefully would work

**Comment by stephenlautier** [comment]
@alecrt 1.1.2 should work using `@aspnet/signalr` 1.1.4 so far

(untested with SSR yet)
